# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pharmacy_pb2 as pharmacy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pharmacy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PharmacyServiceStub(object):
    """=========================================================================
    ORIGINAL: PharmacyService — defined by the base project group (Project 2)
    =========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDrug = channel.unary_unary(
                '/pharmacy.PharmacyService/AddDrug',
                request_serializer=pharmacy__pb2.AddDrugRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DrugResponse.FromString,
                _registered_method=True)
        self.GetDrug = channel.unary_unary(
                '/pharmacy.PharmacyService/GetDrug',
                request_serializer=pharmacy__pb2.GetDrugRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DrugResponse.FromString,
                _registered_method=True)
        self.UpdateStock = channel.unary_unary(
                '/pharmacy.PharmacyService/UpdateStock',
                request_serializer=pharmacy__pb2.UpdateStockRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DrugResponse.FromString,
                _registered_method=True)
        self.DeleteDrug = channel.unary_unary(
                '/pharmacy.PharmacyService/DeleteDrug',
                request_serializer=pharmacy__pb2.DeleteDrugRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListDrugs = channel.unary_unary(
                '/pharmacy.PharmacyService/ListDrugs',
                request_serializer=pharmacy__pb2.ListDrugsRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.ListDrugsResponse.FromString,
                _registered_method=True)
        self.GetLowStock = channel.unary_unary(
                '/pharmacy.PharmacyService/GetLowStock',
                request_serializer=pharmacy__pb2.LowStockRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.ListDrugsResponse.FromString,
                _registered_method=True)


class PharmacyServiceServicer(object):
    """=========================================================================
    ORIGINAL: PharmacyService — defined by the base project group (Project 2)
    =========================================================================
    """

    def AddDrug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDrug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDrug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDrugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLowStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PharmacyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDrug': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDrug,
                    request_deserializer=pharmacy__pb2.AddDrugRequest.FromString,
                    response_serializer=pharmacy__pb2.DrugResponse.SerializeToString,
            ),
            'GetDrug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDrug,
                    request_deserializer=pharmacy__pb2.GetDrugRequest.FromString,
                    response_serializer=pharmacy__pb2.DrugResponse.SerializeToString,
            ),
            'UpdateStock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStock,
                    request_deserializer=pharmacy__pb2.UpdateStockRequest.FromString,
                    response_serializer=pharmacy__pb2.DrugResponse.SerializeToString,
            ),
            'DeleteDrug': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDrug,
                    request_deserializer=pharmacy__pb2.DeleteDrugRequest.FromString,
                    response_serializer=pharmacy__pb2.DeleteResponse.SerializeToString,
            ),
            'ListDrugs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDrugs,
                    request_deserializer=pharmacy__pb2.ListDrugsRequest.FromString,
                    response_serializer=pharmacy__pb2.ListDrugsResponse.SerializeToString,
            ),
            'GetLowStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLowStock,
                    request_deserializer=pharmacy__pb2.LowStockRequest.FromString,
                    response_serializer=pharmacy__pb2.ListDrugsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pharmacy.PharmacyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pharmacy.PharmacyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PharmacyService(object):
    """=========================================================================
    ORIGINAL: PharmacyService — defined by the base project group (Project 2)
    =========================================================================
    """

    @staticmethod
    def AddDrug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.PharmacyService/AddDrug',
            pharmacy__pb2.AddDrugRequest.SerializeToString,
            pharmacy__pb2.DrugResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDrug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.PharmacyService/GetDrug',
            pharmacy__pb2.GetDrugRequest.SerializeToString,
            pharmacy__pb2.DrugResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.PharmacyService/UpdateStock',
            pharmacy__pb2.UpdateStockRequest.SerializeToString,
            pharmacy__pb2.DrugResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDrug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.PharmacyService/DeleteDrug',
            pharmacy__pb2.DeleteDrugRequest.SerializeToString,
            pharmacy__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDrugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.PharmacyService/ListDrugs',
            pharmacy__pb2.ListDrugsRequest.SerializeToString,
            pharmacy__pb2.ListDrugsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLowStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.PharmacyService/GetLowStock',
            pharmacy__pb2.LowStockRequest.SerializeToString,
            pharmacy__pb2.ListDrugsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TwoPhaseParticipantServiceStub(object):
    """=========================================================================
    [PROJECT 3] TWO-PHASE COMMIT PROTOCOL — Q1 (Vote Phase) + Q2 (Decision Phase)

    Architecture:
    TwoPhaseParticipantService — runs on ALL 5 nodes on port 50052
    VoteRequest  : coordinator asks each participant "can you commit?" (Q1)
    GlobalCommit : coordinator tells all participants to locally commit  (Q2)
    GlobalAbort  : coordinator tells all participants to locally abort   (Q2)

    CoordinatorService — runs ONLY on Node 1 (api-server-a) on port 50053
    UpdateStock2PC : client calls this to trigger a full 2PC UpdateStock

    The coordinator (decision phase) drives the protocol by calling each
    participant's VoteRequest/GlobalCommit/GlobalAbort via gRPC — including
    calling its OWN participant service on localhost:50052, satisfying the
    assignment requirement that voting and decision phases on the same node
    communicate over gRPC even within the same container.
    =========================================================================

    Participant service: handles vote and decision RPCs on all 5 nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoteRequest = channel.unary_unary(
                '/pharmacy.TwoPhaseParticipantService/VoteRequest',
                request_serializer=pharmacy__pb2.VoteRequestMsg.SerializeToString,
                response_deserializer=pharmacy__pb2.VoteResponseMsg.FromString,
                _registered_method=True)
        self.GlobalCommit = channel.unary_unary(
                '/pharmacy.TwoPhaseParticipantService/GlobalCommit',
                request_serializer=pharmacy__pb2.GlobalDecisionMsg.SerializeToString,
                response_deserializer=pharmacy__pb2.GlobalDecisionAck.FromString,
                _registered_method=True)
        self.GlobalAbort = channel.unary_unary(
                '/pharmacy.TwoPhaseParticipantService/GlobalAbort',
                request_serializer=pharmacy__pb2.GlobalDecisionMsg.SerializeToString,
                response_deserializer=pharmacy__pb2.GlobalDecisionAck.FromString,
                _registered_method=True)


class TwoPhaseParticipantServiceServicer(object):
    """=========================================================================
    [PROJECT 3] TWO-PHASE COMMIT PROTOCOL — Q1 (Vote Phase) + Q2 (Decision Phase)

    Architecture:
    TwoPhaseParticipantService — runs on ALL 5 nodes on port 50052
    VoteRequest  : coordinator asks each participant "can you commit?" (Q1)
    GlobalCommit : coordinator tells all participants to locally commit  (Q2)
    GlobalAbort  : coordinator tells all participants to locally abort   (Q2)

    CoordinatorService — runs ONLY on Node 1 (api-server-a) on port 50053
    UpdateStock2PC : client calls this to trigger a full 2PC UpdateStock

    The coordinator (decision phase) drives the protocol by calling each
    participant's VoteRequest/GlobalCommit/GlobalAbort via gRPC — including
    calling its OWN participant service on localhost:50052, satisfying the
    assignment requirement that voting and decision phases on the same node
    communicate over gRPC even within the same container.
    =========================================================================

    Participant service: handles vote and decision RPCs on all 5 nodes
    """

    def VoteRequest(self, request, context):
        """Q1 — Vote phase: coordinator sends proposed UpdateStock, participant votes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalCommit(self, request, context):
        """Q2 — Decision phase: coordinator delivers the global commit or abort
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPhaseParticipantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteRequest,
                    request_deserializer=pharmacy__pb2.VoteRequestMsg.FromString,
                    response_serializer=pharmacy__pb2.VoteResponseMsg.SerializeToString,
            ),
            'GlobalCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalCommit,
                    request_deserializer=pharmacy__pb2.GlobalDecisionMsg.FromString,
                    response_serializer=pharmacy__pb2.GlobalDecisionAck.SerializeToString,
            ),
            'GlobalAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalAbort,
                    request_deserializer=pharmacy__pb2.GlobalDecisionMsg.FromString,
                    response_serializer=pharmacy__pb2.GlobalDecisionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pharmacy.TwoPhaseParticipantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pharmacy.TwoPhaseParticipantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPhaseParticipantService(object):
    """=========================================================================
    [PROJECT 3] TWO-PHASE COMMIT PROTOCOL — Q1 (Vote Phase) + Q2 (Decision Phase)

    Architecture:
    TwoPhaseParticipantService — runs on ALL 5 nodes on port 50052
    VoteRequest  : coordinator asks each participant "can you commit?" (Q1)
    GlobalCommit : coordinator tells all participants to locally commit  (Q2)
    GlobalAbort  : coordinator tells all participants to locally abort   (Q2)

    CoordinatorService — runs ONLY on Node 1 (api-server-a) on port 50053
    UpdateStock2PC : client calls this to trigger a full 2PC UpdateStock

    The coordinator (decision phase) drives the protocol by calling each
    participant's VoteRequest/GlobalCommit/GlobalAbort via gRPC — including
    calling its OWN participant service on localhost:50052, satisfying the
    assignment requirement that voting and decision phases on the same node
    communicate over gRPC even within the same container.
    =========================================================================

    Participant service: handles vote and decision RPCs on all 5 nodes
    """

    @staticmethod
    def VoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.TwoPhaseParticipantService/VoteRequest',
            pharmacy__pb2.VoteRequestMsg.SerializeToString,
            pharmacy__pb2.VoteResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.TwoPhaseParticipantService/GlobalCommit',
            pharmacy__pb2.GlobalDecisionMsg.SerializeToString,
            pharmacy__pb2.GlobalDecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.TwoPhaseParticipantService/GlobalAbort',
            pharmacy__pb2.GlobalDecisionMsg.SerializeToString,
            pharmacy__pb2.GlobalDecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServiceStub(object):
    """Coordinator service: receives UpdateStock2PC from a client and drives 2PC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateStock2PC = channel.unary_unary(
                '/pharmacy.CoordinatorService/UpdateStock2PC',
                request_serializer=pharmacy__pb2.UpdateStockRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DrugResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Coordinator service: receives UpdateStock2PC from a client and drives 2PC
    """

    def UpdateStock2PC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateStock2PC': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStock2PC,
                    request_deserializer=pharmacy__pb2.UpdateStockRequest.FromString,
                    response_serializer=pharmacy__pb2.DrugResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pharmacy.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pharmacy.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Coordinator service: receives UpdateStock2PC from a client and drives 2PC
    """

    @staticmethod
    def UpdateStock2PC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoordinatorService/UpdateStock2PC',
            pharmacy__pb2.UpdateStockRequest.SerializeToString,
            pharmacy__pb2.DrugResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
